services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDMINE_URL: http://host.docker.internal:3000
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"